config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"

  # Routes for Devise sessions and logout
  devise_scope :user do
    get '/users/sign_out', to: 'devise/sessions#destroy'
  end

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Routes for Skill model
  resources :skills

  # Routes for Degree model
  resources :degrees

  # Routes for WorkExperience model
  resources :work_experiences

  # Routes for Contact model
  resources :contacts, only: %i[new create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :name, validate: true
  attribute :last_name, validate: true
  attribute :email, validate: true
  attribute :message

 def headers
    {
      subject: "My Contact Form",
      to: 'youri.soposki@gmail.com',
      from: %("#{name} #{last_name}" <#{email}>)
    }
  end
end

app/models/degree.rb
class Degree < ApplicationRecord
  belongs_to :user, optional: true

  validates :institution, presence: true
  validates :degree, presence: true
  validates :start_date, presence: true
  validates :end_date, presence: true
  validate :end_date_after_start_date
  validates :description, presence: true

  private

  def end_date_after_start_date
    return if end_date.blank? || start_date.blank?
    errors.add(:end_date, "must be after the start date") if end_date < start_date
  end
end

app/models/skill.rb
class Skill < ApplicationRecord
  belongs_to :user, optional: true
  has_one_attached :icon

  validates :name, presence: true
  validates :level, inclusion: { in: %w(beginner intermediate advanced expert) }
  validates :section, inclusion: { in: %w(soft hard) }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable, and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validate :valid_email_for_registration, on: :create

  private

  def valid_email_for_registration
    unless email == 'youri.soposki@gmail.com'
      errors.add(:base, 'Email is not allowed to register.')
    end
  end
end

app/models/work_experience.rb
class WorkExperience < ApplicationRecord
  belongs_to :user, optional: true

  validates :title, presence: true
  validates :company, presence: true
  validates :description, presence: true
  validates :start_date, presence: true
  validates :end_date, presence: true
  validate :end_date_after_start_date

  private

  def end_date_after_start_date
    return if end_date.blank? || start_date.blank?
    errors.add(:end_date, "must be after the start date") if end_date < start_date
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def create
    @name = params[:contact_form][:name]
    @last_name = params[:contact_form][:last_name]
    @email = params[:contact_form][:email]
    @message = params[:contact_form][:message]

    # Perform any necessary actions with the form data
    NotifierMailer.simple_message(@name, @last_name, @email, @message).deliver_now
    flash[:notice] = "Your message has been sent successfully."
    redirect_to :root
end
end

app/controllers/degrees_controller.rb
class DegreesController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_degree, only: [:show, :edit, :update, :destroy]

  # GET /degrees
  def index
    @degrees = Degree.order(end_date: :desc)
  end

  # GET /degrees/1
  def show
    @degree = Degree.find(params[:id])
  end

  # GET /degrees/new
  def new
    @degree = Degree.new
  end

  # GET /degrees/1/edit
  def edit
    @degree = Degree.find(params[:id])
  end

  # POST /degrees
  def create
    @degree = Degree.new(degree_params)
    if @degree.save
      redirect_to @degree, notice: 'Degree was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /degrees/1
  def update
    if @degree.update(degree_params)
      redirect_to @degree, notice: 'Degree was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /degrees/1
  def destroy
    @degree = Degree.find(params[:id])
    @degree.destroy
    respond_to do |format|
    format.html { redirect_to degrees_url, notice: 'Degree was successfully destroyed.' }
    format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_degree
      @degree = Degree.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def degree_params
      params.require(:degree).permit(:institution, :degree, :start_date, :end_date, :description)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/skills_controller.rb
# app/controllers/skills_controller.rb
class SkillsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_skill, only: [:show, :edit, :update, :destroy]

  # GET /skills
  def index
    @skills = Skill.all
  end

  # GET /skills/1
  def show
    @skill = Skill.find(params[:id])
  end

  # GET /skills/new
  def new
    @skill = Skill.new
  end

  # GET /skills/1/edit
  def edit
    @skill = Skill.find(params[:id])
  end

  # POST /skills
  def create
    @skill = Skill.new(skill_params)
    if @skill.save
      redirect_to @skill, notice: 'Skill was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /skills/1
  def update
    if @skill.update(skill_params)
      redirect_to @skill, notice: 'Skill was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /skills/1
def destroy
  @skill = Skill.find(params[:id])
  @skill.destroy
  respond_to do |format|
    format.html { redirect_to skills_url, notice: 'Skill was successfully destroyed.' }
    format.json { head :no_content }
  end
end



  private
    # Use callbacks to share common setup or constraints between actions.
    def set_skill
      @skill = Skill.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def skill_params
      params.require(:skill).permit(:name, :level, :section, :icon, :description) # Ajoutez :icon aux paramètres autorisés
    end
end

app/controllers/work_experiences_controller.rb
class WorkExperiencesController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_work_experience, only: [:show, :edit, :update, :destroy]

  # GET /work_experiences
  def index
    @work_experiences = WorkExperience.all.order(end_date: :desc)
  end

  # GET /work_experiences/1
  def show
    @work_experience = WorkExperience.find(params[:id])
  end

  # GET /work_experiences/new
  def new
    @work_experience = WorkExperience.new
  end

  # GET /work_experiences/1/edit
  def edit
    @work_experience = WorkExperience.find(params[:id])
  end

  # POST /work_experiences
  def create
    @work_experience = WorkExperience.new(work_experience_params)
    if @work_experience.save
      redirect_to @work_experience, notice: 'Work experience was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /work_experiences/1
  def update
    if @work_experience.update(work_experience_params)
      redirect_to @work_experience, notice: 'Work experience was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /work_experiences/1
  def destroy
    @work_experience = WorkExperience.find(params[:id])
    @work_experience.destroy
    respond_to do |format|
      format.html { redirect_to work_experiences_url, notice: 'Work experience was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_work_experience
      @work_experience = WorkExperience.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def work_experience_params
      params.require(:work_experience).permit(:title, :company, :description, :start_date, :end_date)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/contacts/new.html.erb
<body>
    <div class="banner position-relative d-flex justify-content-center align-items-center mb-4">
      <img src="https://images.unsplash.com/photo-1550859492-d5da9d8e45f3?q=80&w=2940&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D" alt="skills banner">
      <h1 class="text-white position-absolute bottom-0 start-50 translate-middle-x mb-4">CONTACT</h1>
    </div>
  <div class="contact" style="margin-top: 70px;">
  <div id="container-form">
    <%= form_with scope: :contact_form, url: contacts_path, method: :post, local: true, class: "container" do |form| %>

      <div class="form-group row">
        <div class="col-md-6">
          <%= form.label :name %>
          <%= form.text_field :name, class: "form-control form-control-sm", id: "name_input", required: true %>
        </div>

        <div class="col-md-6 form-group">
          <%= form.label :email %>
          <%= form.email_field :email, class: "form-control form-control-sm", id: "email_input", required: true %>
        </div>
      </div>

      <div class="form-group">
        <%= form.label :message %>
        <%= form.text_area :message, class: "form-control form-control-sm", id: "message_input", required: true, rows: 4 %>
      </div>

      <%= form.submit "Submit", class: "btn btn-sm", id: "form_button" %>

    <% end %>
    </div>
  </div>
</body>

<style>
      .title{
        font-family: "Cutive Mono", serif;
      }

      .banner {
        overflow: hidden;
        position: relative;
        height: 400px; /* Hauteur de la bannière */
        width: 100%; /* Largeur de la bannière */
      }

      .banner h1 {
        position: absolute;
        top: 50%; /* Centrage vertical */
        left: 50%; /* Centrage horizontal */
        transform: translate(-50%, -50%); /* Ajustement pour centrer parfaitement */
        z-index: 1;
        color: white;
        font-family: "Cutive Mono", serif;
        font-size: 70px;
}

      .banner img {
        object-fit: cover;
        height: 100%;
        width: 100%;
      }

      #container-form {
        border: 1px solid black;
        max-width: 500px;
        margin: 20px auto;
        padding: 10px;
      }

      .form-control-sm {
        font-size: 0.8em;
      }

      /* Pour les écrans de petite taille */
@media (max-width: 768px) {

  .banner h1 {
    font-size: 30px;
  }

  #container-form {
    margin: 20px 10px; /* Ajout d'une marge sur les côtés pour les petits écrans */
  }
}

</style>

app/views/degrees/edit.html.erb
<%= render "form", degree: @degree %>

app/views/degrees/index.html.erb
<body>
  <!-- Bannière avec superposition du h1 -->
  <div class="banner position-relative mb-4">
    <img src="https://images.unsplash.com/photo-1579547621869-0ddb5f237392?q=80&w=3870&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D" alt="degree banner">
    <h1 class="text-white position-absolute bottom-0 start-50 translate-middle-x mb-4">DEGREES</h1>
  </div>

  <div class="container">
    <% @degrees.each do |degree| %>
      <div class="row mb-4">
        <div class="col-12">
          <div class="card text-center">
            <div class="card-body">
              <div class="skill-details">
                <h2 class="card-title"><b><%= degree.degree %></b></h2>
                <p>@<%= degree.institution %></p>
                <p>From <%= degree.start_date.strftime('%d %B %Y') %> to <%= degree.end_date ? degree.end_date.strftime('%d %B %Y') : 'Présent' %></p>
                <%= link_to "Details", degree, class: "btn" %>
              </div>
            </div>
          </div>
        </div>
      </div>
    <% end %>
    <% if user_signed_in? %> <!-- Vérifie si un utilisateur est connecté -->
      <%= link_to "Add +1", new_degree_path, class: "btn" %>
    <% end %>
  </div>
</body>

<style>
  .banner {
    overflow: hidden;
    position: relative;
    height: 400px; /* Hauteur de la bannière */
    width: 100%; /* Largeur de la bannière */
  }

  .banner img {
    object-fit: cover;
    height: 100%;
    width: 100%;
  }

  .banner h1 {
    position: absolute;
    top: 50%; /* Centrage vertical */
    left: 50%; /* Centrage horizontal */
    transform: translate(-50%, -50%); /* Ajustement pour centrer parfaitement */
    z-index: 1;
    color: white;
    font-family: "Cutive Mono", serif;
    font-size: 70px;
    color: black;
  }

@media (max-width: 768px) {

  .banner h1 {
    font-size: 30px;
  }

  .card-body {
    font-size: 12px;
  }

  .card-title {
    font-size: 18px;
  }

}
</style>

app/views/degrees/new.html.erb
<%= render "form", degree: @degree %>

app/views/degrees/show.html.erb
<body>
  <!-- Bannière avec superposition du h1 -->
  <div class="banner position-relative mb-4">
    <img src="https://images.unsplash.com/photo-1579547621869-0ddb5f237392?q=80&w=3870&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D" alt="degree banner">
    <h1 class="text-white position-absolute bottom-0 start-50 translate-middle-x mb-4">DEGREE</h1>
  </div>

  <div class="container">
    <div class="row justify-content-center">
      <div class="col-md-8">
        <div class="card text-center">
          <div class="card-body">
            <h2 class="text-center mb-4"><%= @degree.degree %></h2>

            <dl class="mb-4">
              <dt class="mb-2"><strong>Institution:</strong></dt>
              <dd class="mb-4"><%= @degree.institution %></dd>

              <dt class="mb-2"><strong>Description:</strong></dt>
              <div class="description-text">
                <dd class="mb-4"><%= @degree.description %></dd>
              </div>

              <dt></dt>
              <dd class="d-inline-block mr-2">From <%= @degree.start_date.strftime('%d %B %Y') %></dd>
              <dd class="d-inline-block">to <%= @degree.end_date ? @degree.end_date.strftime('%d %B %Y') : 'Présent' %></dd>
            </dl>

            <div class="text-center mt-3">
  <% if user_signed_in? %> <!-- Vérifie si un utilisateur est connecté -->
    <%= link_to "Edit", edit_degree_path(@degree), class: "btn btn-sm mr-2" %>
    <%= turbo_frame_tag "degree_#{@degree.id}" do %>
      <%= button_to "Delete", @degree, method: :delete, data: { confirm: "Êtes-vous sûr de vouloir supprimer ce diplôme ?" }, class: "btn btn-sm mr-2" %>
    <% end %> <!-- Fermeture correcte de la balise turbo_frame_tag -->
  <% end %>
  <%= link_to "Back", degrees_path, class: "btn btn-sm" %>
</div>

          </div>
        </div>
      </div>
    </div>
  </div>
</body>

<style>
  .banner {
    overflow: hidden;
    position: relative;
    height: 400px; /* Hauteur de la bannière */
    width: 100%; /* Largeur de la bannière */
  }

  .banner img {
    object-fit: cover;
    height: 100%;
    width: 100%;
  }

  .banner h1 {
    position: absolute;
    top: 50%; /* Centrage vertical */
    left: 50%; /* Centrage horizontal */
    transform: translate(-50%, -50%); /* Ajustement pour centrer parfaitement */
    z-index: 1;
    color: white;
    font-family: "Cutive Mono", serif;
    font-size: 70px;
  }

  .description-text {
    text-align: justify;
  }

  @media (max-width: 768px) {

    .banner h1 {
      font-size: 30px;
    }

    .card-body {
      font-size: 12px;
    }

    h2 {
      font-size: 18px;
    }
  }
</style>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>YouriCv</title>
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <!-- jQuery -->
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>

  <!-- Popper.js -->
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js"></script>

  <!-- CSS de Bootstrap -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">

  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>
  <%= javascript_include_tag "application", type: "module" %>
  <link href='https://fonts.googleapis.com/css?family=Lato' rel='stylesheet'>
</head>

<body>

<nav class="navbar navbar-expand-lg navbar-light navbar-fixed">
  <div class="container-fluid">
    <!-- Groupe de gauche -->
    <div class="navbar-header me-auto">
      <i class="fa-solid fa-code fa-fade fa-2xl" style="color: #000000;"></i>
    </div>

    <!-- Bouton pour le menu déroulant (version mobile) -->
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <!-- Groupe central -->
    <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
      <ul class="navbar-nav mx-auto">
        <li class="nav-item">
          <%= link_to "Home", root_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Skills", skills_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Work-Experiences", work_experiences_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Degrees", degrees_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Contact", new_contact_path, class: "nav-link" %>
        </li>
      </ul>
    </div>

    <!-- Groupe de droite -->
    <div class="ml-auto">
      <ul class="navbar-nav">
        <li class="nav-item">
          <% if user_signed_in? %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "btn-log nav-link" %>
          <% else %>
            <%= link_to "Login", new_user_session_path, class: "btn-log nav-link" %>
          <% end %>
        </li>
      </ul>
    </div>
  </div>
</nav>


  <!-- Affichage des messages flash -->
  <% if notice %>
    <div class="alert alert-success">
      <%= notice %>
    </div>
  <% elsif alert %>
    <div class="alert alert-danger">
      <%= alert %>
    </div>
  <% end %>

  <%= yield %>

  <footer class="bg-dark text-center text-white">
    <div class="container p-4 pb-0">
      <section class="mb-4">
        <!-- Vos icônes pour les réseaux sociaux -->
        <a href="https://www.linkedin.com/in/youri-soposki-424668218/" target="_blank" role="button"><i class="fa-brands fa-linkedin fa-flip fa-2xl" style="color: #ffffff;"></i></a>
        <a href="https://github.com/YouriSpk" target="_blank" role="button"><i class="fa-brands fa-square-github fa-spin fa-spin-reverse fa-2xl" style="color: #ffffff;"></i></a>
      </section>
    </div>
    <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2); font-size: 10px;">
      © 2024 Youri Soposki - All right reserved
    </div>
  </footer>

  <!-- JavaScript de Bootstrap -->
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>

  <!-- Votre CSS personnalisé -->
  <style>
    @import url('https://fonts.googleapis.com/css?family=Cutive+Mono');

    *,
    *:before,
    *:after {
      box-sizing: border-box;
    }

    html {
      font-size: 18px;
    }

    body {
      font-family: "Cutive Mono", serif;
      font-size: 1.2em;
      line-height: 1.6;
      background: #d6d2d2;
      overflow-x: hidden;
      margin-top: 70px; /* Ajout de cette marge pour décaler le contenu en dessous de la navbar */
    }

    .navbar-fixed {
      position: fixed;
      top: 0;
      left: 0;
      width: 100%;
      z-index: 1000; /* Assurez-vous que le z-index est supérieur à celui des autres éléments pour qu'il apparaisse au-dessus */
    }

    .container {
      position: relative; /* Ajout de position relative */
      z-index: 1; /* Assurez-vous que le z-index est supérieur à celui de la navbar */
    }
  </style>

</body>
</html>

app/views/skills/_form.html.erb
<%= simple_form_for(@skill, html: { class: 'skill-form', multipart: true }) do |f| %>
  <%= f.error_notification %>

  <div class="field">
    <%= f.input :name %>
  </div>

  <div class="field">
    <%= f.label :level %>
    <%= f.collection_select :level, ['beginner', 'intermediate', 'advanced', 'expert'], :itself, :capitalize, {}, class: 'form-control' %>
  </div>

  <div class="field">
    <%= f.label :section %>
    <%= f.collection_select :section, ['soft', 'hard'], :itself, :capitalize, {}, class: 'form-control' %>
  </div>

  <div class="field">
    <%= f.input :description %>
  </div>

  <!-- Champ pour l'icône -->
  <div class="field">
    <%= f.label :icon %>
    <%= f.file_field :icon, class: 'form-control' %>
  </div>

  <div class="actions">
    <%= f.submit class: "btn" %>
  </div>

  <% if @skill.persisted? %>
    <%= link_to 'Destroy', skill_path(@skill), method: :delete, data: { confirm: 'Are you sure?' } %>
  <% end %>

<% end %>

app/views/skills/edit.html.erb
<%= render "form", skill: @skill %>

app/views/skills/new.html.erb
<%= render "form", skill: @skill %>

app/views/skills/show.html.erb
<body>
  <!-- Bannière avec superposition du h1 -->
  <div class="banner position-relative">
    <img src="https://images.unsplash.com/photo-1614849286521-4c58b2f0ff15?q=80&w=3870&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D" alt="skills banner">
    <h1 class="text-white position-absolute bottom-0 start-50 translate-middle-x mb-4 text-center">SKILLS DETAILS</h1>
  </div>

  <div class="container d-flex justify-content-center align-items-center flex-column mt-5 no-padding">

    <div class="card w-75">
      <div class="card-body">
        <div class="skill-details">
          <% if @skill.icon.attached? %>
            <div class="skill-icon text-center mb-4">
              <%= image_tag @skill.icon %>
            </div>
          <% end %>
          <div class="text-center mb-4">
            <p><strong>Name :</strong> <%= @skill.name %></p>
            <p><strong>Level :</strong> <%= @skill.level %></p>
            <p><strong>Section :</strong> <%= @skill.section %></p>
            <p><strong>Description :</strong></p>
              <div class="description-text">
                <%= @skill.description %>
              </div>
            </div>
          <div class="text-center mt-3">
            <% if user_signed_in? %>
              <%= link_to 'Edit', edit_skill_path(@skill), class: "btn btn-sm mr-2" %>
              <%= turbo_frame_tag "skill_#{@skill.id}" do %>
              <%= button_to "Delete", skill_path(@skill), method: :delete, data: { confirm: "Êtes-vous sûr de vouloir supprimer cette compétence ?" }, class: "btn btn-sm mr-2" %>
              <% end %>
            <% end %>
            <%= link_to 'Back', skills_path, class: "btn btn-sm" %>
          </div>
        </div>
      </div>
    </div>
  </div>
</body>

<style>
  .banner {
    overflow: hidden;
    position: relative;
    height: 400px;
    width: 100%;
  }

  .banner img {
    object-fit: cover;
    height: 100%;
    width: 100%;
  }

  .banner h1 {
    position: absolute;
    top: 50%;
    left: 50%;
    transform: translate(-50%, -50%);
    z-index: 1;
    color: white;
    font-family: "Cutive Mono", serif;
    font-size: 70px;
  }

  .no-padding {
    padding-left: 0 !important;
    padding-right: 0 !important;
  }

  .skill-icon img {
    width: 120px;
    height: 120px;
  }

  .description-text {
    text-align: justify;
  }

  @media (max-width: 768px) {
    .skill-icon img {
      width: 50px;
      height: 50px;
    }

    .banner h1 {
      font-size: 30px;
    }

    .card-body{
    font-size: 12px
  }
}
</style>

app/views/work_experiences/edit.html.erb
<%= render "form", work_experience: @work_experience %>

app/views/work_experiences/new.html.erb
<%= render "form", work_experience: @work_experience %>

app/views/work_experiences/show.html.erb
<body>
  <!-- Bannière avec superposition du h1 -->
  <div class="banner position-relative">
    <img src="https://images.unsplash.com/photo-1614854262204-ac42b8c25c0e?q=80&w=3870&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D" alt="work experience banner">
    <h1 class="text-white position-absolute bottom-0 start-50 translate-middle-x mb-4 text-center">WORK EXPERIENCES</h1>
  </div>

  <div class="container d-flex justify-content-center align-items-center flex-column mt-5 no-padding">
    <div class="card w-75">
      <div class="card-body">
        <div class="work-experience-details">
          <div class="text-center mb-4">
            <h2><strong>Title :</strong> <%= @work_experience.title %></h2>
            <p><strong>Company :</strong> @<%= @work_experience.company %></p>
            <p><strong>Description :</strong></p>
            <div class="description-text">
              <%= @work_experience.description %>
            </div>
            <p class="mt-4">From <%= @work_experience.start_date.strftime('%d %B %Y') %> to <%= @work_experience.end_date ? @work_experience.end_date.strftime('%d %B %Y') : 'Présent' %></p>
          </div>
          <div class="text-center mt-3">
            <% if user_signed_in? %>
              <%= link_to "Edit", edit_work_experience_path(@work_experience), class: "btn btn-primary btn-sm mr-2" %>
              <%= turbo_frame_tag "work_experience_#{@work_experience.id}" do %>
              <%= button_to "Delete", work_experience_path(@work_experience), method: :delete, data: { confirm: "Êtes-vous sûr de vouloir supprimer cette expérience professionnelle ?" }, class: "btn btn-sm mr-2" %>
              <% end %>
            <% end %>
            <%= link_to "Back", work_experiences_path, class: "btn btn-secondary btn-sm" %>
          </div>
        </div>
      </div>
    </div>
  </div>
</body>

<style>
  .banner {
    overflow: hidden;
    position: relative;
    height: 400px;
    width: 100%;
  }

  .banner img {
    object-fit: cover;
    height: 100%;
    width: 100%;
  }

  .banner h1 {
    position: absolute;
    top: 50%;
    left: 50%;
    transform: translate(-50%, -50%);
    z-index: 1;
    color: white;
    font-family: "Cutive Mono", serif;
    font-size: 70px;
  }

  .no-padding {
    padding-left: 0 !important;
    padding-right: 0 !important;
  }

  .work-experience-icon img {
    width: 120px;
    height: 120px;
  }

  .description-text {
    text-align: justify;
  }

  @media (max-width: 768px) {

    .banner h1 {
      font-size: 30px;
    }

    .card-body{
      font-size: 12px;
    }

    h2 {
      font-size: 18px;
    }
  }
</style>